server:
  port: 8833
spring:
  application:
    name: mall-unqid

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_unqid?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456