spring:
  application:
    name: mall-common

#  security:
#    oauth2:
#      # 资源服务器配置
#      resourceserver:
#        jwt:
#          # Jwt中claims的iss属性，也就是jwt的签发地址，即认证服务器的根路径
#          # 资源服务器会进一步的配置，通过该地址获取公钥以解析jwt
#          #          issuer-uri: http://127.0.0.1:9001/
#          jwk-set-uri: http://127.0.0.1:9001/oauth2/jwks


