
spring:
  application:
    name: mall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_goods?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  security:
    oauth2:
      # 资源服务器配置
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9001/oauth2/jwks
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-server
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  data-source-proxy-mode: AT

logging:
  level:
    io:
      seata: info

server:
  port: 8085