server:
  port: 9001

logging:
  level:
    org.springframework.security: trace

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: oauth-server
  redis:
    date:
      host: 127.0.0.1
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall-user?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

jwt:
  tokenHeader: Authorization
  secret: 4567822
  expiration: 604800
  tokenHead: 'Bearer '